apiVersion: apps/v1
kind: Deployment
metadata:
  name: karmada-controller-manager
  namespace: karmada-system
  labels:
    app: karmada-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karmada-controller-manager
  template:
    metadata:
      labels:
        app: karmada-controller-manager
    spec:
      serviceAccountName: karmada-controller-manager
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
      nodeSelector:
        kubernetes.io/hostname: cloud
      containers:
        - name: karmada-controller-manager
          image: ubuntu:5000/karmada-controller-manager:v0.7.0-111-g8effddd
          imagePullPolicy: IfNotPresent
          command:
            - /bin/karmada-controller-manager
            - --kubeconfig=/etc/kubeconfig
            - --bind-address=0.0.0.0
            - --cluster-status-update-frequency=10s
            - --secure-port=10357
            - --v=4
          volumeMounts:
          - name: kubeconfig
            subPath: kubeconfig
            mountPath: /etc/kubeconfig
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig

