apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-karmada
  placement:
    clusterAffinity:
      clusterNames:
        - k8s82
        - k8s251

