apiVersion: policy.karmada.io/v1alpha1
kind: ReplicaSchedulingPolicy
metadata:
  name: foo
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: default
      name: nginx-karmada
  totalReplicas: 3
  preferences:
    staticWeightList:
      - targetCluster:
          clusterNames: [k8s251]
        weight: 1
      - targetCluster:
          clusterNames: [k8s82]
        weight: 2
